<a href="https://colab.research.google.com/github/imammarzuki/pandas_dasar/blob/main/18_BroadcastingOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pandas DataFrame â€“ Memahami Broadcasting Operation

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df=pd.read_csv("drive/MyDrive/pandas_dasar/Data/nba.csv")
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
df["Age"]

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [7]:
df["Age"].add(5)

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
       ...
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [8]:
df["Age"] + 5

0      30.0
1      30.0
2      32.0
3      27.0
4      34.0
       ...
453    31.0
454    29.0
455    31.0
456    31.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [10]:
#pengurangan
df["Age"].sub(5)
df["Age"] - 5

0      20.0
1      20.0
2      22.0
3      17.0
4      24.0
       ...
453    21.0
454    19.0
455    21.0
456    21.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [11]:
#perkalian
df["Age"].mul(2)
df["Age"] * 2

0      50.0
1      50.0
2      54.0
3      44.0
4      58.0
       ...
453    52.0
454    48.0
455    52.0
456    52.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [12]:
#pembagian
df["Age"].div(2)
df["Age"] / 2

0      12.5
1      12.5
2      13.5
3      11.0
4      14.5
       ...
453    13.0
454    12.0
455    13.0
456    13.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [13]:
df["Salary"]

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [14]:
df["Salary in Million"] = df["Salary"].div(1000000)
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary in Million
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,7.730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,6.796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1.148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               457 non-null    object
 1   Team               457 non-null    object
 2   Number             457 non-null    float64
 3   Position           457 non-null    object
 4   Age                457 non-null    float64
 5   Height             457 non-null    object
 6   Weight             457 non-null    float64
 7   College            373 non-null    object
 8   Salary             446 non-null    float64
 9   Salary in Million  446 non-null    float64
dtypes: float64(5), object(5)
memory usage: 35.9+ KB